### retrieve user in cache

GET {{host}}/user?key=Sergio
Content-Type: application/json
Accept: application/json

### add user in cache

POST {{host}}/user/add
Content-Type: application/json
Accept: application/json

{
  "name": "Sergio"
}